;(function () {
;(function () {
(function(){if(!window.b24form){window.b24form=function(e){b24form.forms=b24form.forms||[];b24form.forms.push(e);if(e.ref&&b24form.Loader&&!this.loaded){this.loaded=true;b24form.Loader.loadJs(e.ref,true)}}}if(window.b24form.Loader){return}function e(){this.requested=false;this.queue=[]}e.prototype={run:function(e){e=e||{};var o=e.resources||{};this.queue.push(e.form);if(!this.requested){var t=this.loadApp.bind(this,o.app);this.requested=true;if(o.polyfill&&!this.checkPolyfills()){this.loadJs(o.polyfill,true,t)}else{t()}}this.loadForms()},loadApp:function(e){if(!e){return}window.b24form.App?this.loadForms():this.loadJs(e,true,this.loadForms.bind(this))},loadForms:function(){if(!this.checkPolyfills()){return}if(!window.b24form.App){return}var e=this.queue;this.queue=[];e.forEach(this.loadForm,this)},loadForm:function(e){b24form.App.initFormScript24(e)},checkPolyfills:function(){return window.fetch&&window.Request&&window.Response&&window.Promise&&Object.assign&&Array.prototype.find&&Array.prototype.includes},loadJs:function(e,o,t){var i=document.createElement("SCRIPT");i.setAttribute("type","text/javascript");i.setAttribute("async","");if(o){i.setAttribute("src",e+"?"+(Date.now()/864e5|0));if(t){i.onload=t}this.appendToHead(i)}else{i.appendChild(document.createTextNode(e));this.appendToHead(i)}},appendToHead:function(e){(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(e)}};window.b24form.Loader=new e})();
//# sourceMappingURL=https://houss.bitrix24.com/bitrix/js/crm/site/form/embed/unit/script.map.js

window.b24form.Loader.run({"form":{"id":"73","sec":"8mwghc","lang":"en","address":"https:\/\/houss.bitrix24.com","views":{"click":{"type":"panel","position":"right","vertical":"bottom"},"auto":{"type":"popup","position":"center","vertical":"bottom","delay":5}},"data":{"language":"en","design":{"style":"modern","dark":true,"shadow":true,"font":{"uri":"https:\/\/fonts.googleapis.com\/css2?family=Open+Sans:wght@100;200;300;400;500;600;700;800;900","family":"Open Sans"},"border":{"bottom":true,"top":false,"left":false,"right":false},"color":{"primary":"#000000ff","primaryText":"#ffffffff","text":"#ffffffff","background":"#000000ff","fieldBorder":"#ffffff0c","fieldBackground":"#000000ff","fieldFocusBackground":"#00000000"}},"title":"","desc":"","buttonCaption":"Send","useSign":false,"date":{"dateFormat":"DD\/MM\/YYYY","dateTimeFormat":"DD\/MM\/YYYY HH:MI:SS","sundayFirstly":false},"currency":{"code":"ZAR","title":"Rand","format":"R#"},"fields":[],"agreements":[],"dependencies":[{"id":"20827","typeId":0,"logic":"or","list":[{"condition":{"target":"DEAL_UF_CRM_63FF1FEA88796","event":"change","value":"14335","operation":"="},"action":{"target":"DEAL_UF_CRM_1676632362","type":"show","value":""}},{"condition":{"target":"DEAL_UF_CRM_63FF1FEA88796","event":"change","value":"17587","operation":"="},"action":{"target":"DEAL_UF_CRM_1676632362","type":"show","value":""}},{"condition":{"target":"DEAL_UF_CRM_1684325333","event":"change","value":"","operation":"any"},"action":{"target":"DEAL_UF_CRM_1729778898","type":"show","value":""}},{"condition":{"target":"DEAL_UF_CRM_1684325333","event":"change","value":"","operation":"any"},"action":{"target":"DEAL_UF_CRM_1729779145","type":"show","value":""}},{"condition":{"target":"DEAL_UF_CRM_63C52CD47A71D","event":"change","value":"","operation":"any"},"action":{"target":"DEAL_UF_CRM_63C52BCC3AB89","type":"show","value":""}},{"condition":{"target":"DEAL_UF_CRM_63C52CD47A71D","event":"change","value":"","operation":"any"},"action":{"target":"DEAL_UF_CRM_1679052359","type":"show","value":""}},{"condition":{"target":"DEAL_UF_CRM_63C52CD47A71D","event":"change","value":"","operation":"any"},"action":{"target":"DEAL_UF_CRM_1679052396","type":"show","value":""}},{"condition":{"target":"DEAL_UF_CRM_63C52CD47A71D","event":"change","value":"","operation":"any"},"action":{"target":"DEAL_UF_CRM_63C52E19B70DD","type":"show","value":""}}]}],"recaptcha":{"use":false}}},"resources":{"app":"https:\/\/cdn.bitrix24.com\/b23490421\/crm\/form\/app.js","polyfill":"https:\/\/cdn.bitrix24.com\/b23490421\/crm\/form\/polyfill.js"}});
})();


})();